clear
cowsay "TUNGGU SEBENTAR BOSSQ!!" |lolcat
toilet "LANJUT INFONYA YAH !!"
Sleep 15
echo "GUNAKAN TOOLS NYA BRO DENGAN BAIK !! SEBENARNYA PUN INFO INI
GAK PENTING !! TAPI LU SENDIRI YANG BUKA FILE INI KAN😂😂😂😂!!
JANGAN LUPA BRO SUSBCRIBE CHANNEL ADMIN => JEJAK TUTORIAL ID "
figlet "SELESAI......!!" |lolcat
exit
fi
